--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/Texter
branches:
  - master
projects:
  Texter:
    path: ""
    icon: "/assets/Logo.png"
    libs:
      - src: poggittestplugins/pmforms/pmforms
        version: ^2.0.0
...
